export default {
 
   "WCS_HOSTNAME" : "34.194.115.169:3737",
   "WCS_HOSTNAME_NOPORT" : "34.194.115.169",
   "WCS_AWS_IMAGE_PATH" : "http://s3.ap-south-1.amazonaws.com/sirius-ep-images/",
   "WCS_IMAGE_FMT": ".jpg",
   "WCS_PRODUCT_DETAILS": "/search/resources/store/",
   "WCS_PRODUCT_DETAILS_APPEND": "/productview/byId/",
   "WCS_CATEGORY_TOP": "/categoryview/@top",
   "WCS_SUB_CATEGORY": "/categoryview/byParentCategory/",
   "WCS_CATEGORY_DETAILS_APPEND": "/productview/byCategory/",
   "WCS_REST_URL": "/wcs/resources/store/",
   "WCS_STORE_ID": "10151",
   "WCS_CATALOG_ID": "10001",
   "WCS_CART": "/cart/",
   "WCS_CART_EXT": "/cart",
   "WCS_DEFAULT": "/@default",
   "WCS_WISHLIST": "/wishlist",
   "WCS_WISHLIST_DELETE": "/wishlist/",
   "WCS_LANG_ID": "-1",
   "WCS_SHIPMODES_APPEND": "/cart/shipping_modes",
   "WCS_INV_AVL": "/inventoryavailability/",
   "WCS_UPDATE_SHIP_INFO": "/cart/@self/shipping_info",
   "WCS_LOG_DIR" : "log/wcs/trace.log",
   "HTML_DIR" : "WebContent/html/",
   "WCS_PRODUCT_SEARCH_BY_KEYWORD" : "/productview/bySearchTerm/",
   "WCS_ADDRESS_DETAILS" : "/person/@self/contact",
   "WCS_CHECKOUT_PROFILE" : "/person/@self/checkoutProfile",
   "WCS_PRODUCT_ADDED" : "Product Added Successfully",
   "SLASH" : "/",
   "SHIP_CALC_USAGE" : "-1,-2,-3,-4,-5,-6,-7",   
   "WCS_SHIP_INFO" : "/cart/@self/shipping_info",
   "MONGO_DB_URL" : "mongodb://admin:passw0rd@ds121716.mlab.com:21716/projectc",
   "WCS_GET_SHOPPINGCART" : "/@self",
   "WCS_UPDATE_CART" : "/update_order_item",
   "WCS_DELETE_CART" : "/delete_order_item",
   "WCS_UPDATECART_CALC_USAGE" : "-1,-2,-3,-4,-5,-6,-7",   
   "WCS_UPDATECART_CALC_ORDER" : "1",  
   "WCS_CART_AT_SELF" : "/cart/@self",
   "WCS_CART_PROMOTIONS" : "/cart/@self/assigned_promotion_code", 
   "WCS_ITEM": "item",

   
   "WCS_ADDRESS_ADDED" : "Address Added Successfully",
   "WCS_ADDRESS_DELETED" : "Address Deleted Successfully",
   "WCS_ADDRESS_UPDATED"  : "Address Updated Successfully",
   "WCS_ADDRESS_SELECTED" : "Address Selected Successfully",
   "WCS_SHIPMODE_SELECTED" : "Ship mode updated successfully",
   
   /*To be got from the UI*/
   "WCS_AUTH_TOKEN" : "12022%2C16Y0w9HO0rAvYKi42p4R3in9WzOQPJ2r8TMIejt6MF%2B4Skkt9f%2F%2FKf71IjRZHCf2cYp2UYzx2i3BGMwV9r5PzWAX5FGAZDsQhAErIsRZEEqWwLMXy6h6ethm5ngU0ijtNQaniaD%2FTOlllsVOreE4PYegQVzOkaXtACIhtQWUZr2RbaMC80nqEG6ORDp6CfKqua3wmqRUbHyqdRhmceBeMDfCs3OziIpsrO7tKefTyJQ%3D",
   "WCS_TRUSTED_TOKEN" : "12022%2CR97hA7x3qfhBXYmRxOYjCaldMf8A9E2b%2BeLYoYpCneY%3D",
 
 };
